import type { PanelConfig, MapLayers, DataSourceId } from '@/types';
import { SITE_VARIANT } from './variant';
// boundary-ignore: isDesktopRuntime is a pure env probe with no service dependencies
import { isDesktopRuntime } from '@/services/runtime';
// boundary-ignore: getSecretState is a pure env/keychain probe with no service dependencies
// import { getSecretState } from '@/services/runtime-config';

const _desktop = isDesktopRuntime();

export const FULL_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Map', enabled: true, priority: 1 },
  'live-news': { name: 'Live News', enabled: false, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: false, priority: 1 },
  'windy-webcams': { name: 'Windy Live Webcam', enabled: false, priority: 2 },
  insights: { name: 'AI Insights', enabled: true, priority: 1 },
  'strategic-posture': { name: 'AI Strategic Posture', enabled: true, priority: 1 },
  forecast: { name: 'AI Forecasts', enabled: true, priority: 1 },
  cii: { name: 'Country Instability', enabled: false, priority: 1 },
  'strategic-risk': { name: 'Strategic Risk Overview', enabled: true, priority: 1 },
  intel: { name: 'Intel Feed', enabled: true, priority: 1 },
  'gdelt-intel': { name: 'Live Intelligence', enabled: true, priority: 1 },
  cascade: { name: 'Infrastructure Cascade', enabled: true, priority: 1 },
  'military-correlation': { name: 'Force Posture', enabled: false, priority: 2 },
  'escalation-correlation': { name: 'Escalation Monitor', enabled: false, priority: 2 },
  'economic-correlation': { name: 'Economic Warfare', enabled: false, priority: 2 },
  'disaster-correlation': { name: 'Disaster Cascade', enabled: true, priority: 2 },
  politics: { name: 'World News', enabled: false, priority: 1 },
  us: { name: 'United States', enabled: false, priority: 1 },
  europe: { name: 'Europe', enabled: false, priority: 1 },
  middleeast: { name: 'Middle East', enabled: false, priority: 1 },
  africa: { name: 'Africa', enabled: false, priority: 1 },
  latam: { name: 'Latin America', enabled: false, priority: 1 },
  asia: { name: 'Asia-Pacific', enabled: false, priority: 1 },
  energy: { name: 'Energy & Resources', enabled: true, priority: 1 },
  gov: { name: 'Government', enabled: false, priority: 1 },
  thinktanks: { name: 'Think Tanks', enabled: false, priority: 1 },
  polymarket: { name: 'Predictions', enabled: false, priority: 1 },
  commodities: { name: 'Metals & Materials', enabled: true, priority: 1 },
  'energy-complex': { name: 'Energy Complex', enabled: true, priority: 1 },
  markets: { name: 'Markets', enabled: true, priority: 1 },
  'stock-analysis': { name: 'Stock Analysis', enabled: false, priority: 1 },
  'stock-backtest': { name: 'Backtesting', enabled: false, priority: 1 },
  'daily-market-brief': { name: 'Daily Market Brief', enabled: false, priority: 1 },
  'chat-analyst': { name: 'Risk Analyst', enabled: false, priority: 1 },
  economic: { name: 'Macro Stress', enabled: true, priority: 1 },
  'trade-policy': { name: 'Trade Policy', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain', enabled: true, priority: 1 },
  finance: { name: 'Financial', enabled: true, priority: 1 },
  tech: { name: 'Technology', enabled: false, priority: 2 },
  crypto: { name: 'Crypto', enabled: false, priority: 2 },
  heatmap: { name: 'Sector Heatmap', enabled: false, priority: 2 },
  ai: { name: 'AI/ML', enabled: false, priority: 2 },
  layoffs: { name: 'Layoffs Tracker', enabled: false, priority: 2 },
  monitors: { name: 'My Monitors', enabled: false, priority: 2 },
  'satellite-fires': { name: 'Fires', enabled: true, priority: 2 },
  'macro-signals': { name: 'Market Regime', enabled: false, priority: 2 },
  'fear-greed': { name: 'Fear & Greed', enabled: false, priority: 2 },
  'macro-tiles': { name: 'Macro Indicators', enabled: false, priority: 2 },
  fsi: { name: 'Financial Stress', enabled: false, priority: 2 },
  'yield-curve': { name: 'Yield Curve', enabled: false, priority: 2 },
  'earnings-calendar': { name: 'Earnings Calendar', enabled: false, priority: 2 },
  'economic-calendar': { name: 'Economic Calendar', enabled: false, priority: 2 },
  'cot-positioning': { name: 'COT Positioning', enabled: false, priority: 2 },
  'hormuz-tracker': { name: 'Hormuz Trade Tracker', enabled: true, priority: 2 },
  'gulf-economies': { name: 'Gulf Economies', enabled: false, priority: 2 },
  'consumer-prices': { name: 'Consumer Prices', enabled: false, priority: 2 },
  'grocery-basket': { name: 'Grocery Index', enabled: false, priority: 2 },
  bigmac: { name: 'Big Mac Index', enabled: false, priority: 2 },
  'fuel-prices': { name: 'Fuel Prices', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: false, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: false, priority: 2 },
  'ucdp-events': { name: 'UCDP Conflict Events', enabled: false, priority: 2 },
  'disease-outbreaks': { name: 'Disease Outbreaks', enabled: false, priority: 2 },
  'social-velocity': { name: 'Social Velocity', enabled: false, priority: 2 },
  giving: { name: 'Global Giving', enabled: false, priority: 2 },
  displacement: { name: 'UNHCR Displacement', enabled: false, priority: 2 },
  climate: { name: 'Climate Anomalies', enabled: true, priority: 2 },
  'population-exposure': { name: 'Population Exposure', enabled: false, priority: 2 },
  'security-advisories': { name: 'Security Advisories', enabled: false, priority: 2 },
  'sanctions-pressure': { name: 'Sanctions Pressure', enabled: false, priority: 2 },
  'defense-patents': { name: 'R&D Signal', enabled: false, priority: 2 },
  'radiation-watch': { name: 'Radiation Watch', enabled: false, priority: 2 },
  'thermal-escalation': { name: 'Thermal Escalation', enabled: false, priority: 2 },
  'oref-sirens': { name: 'Israel Sirens', enabled: false, priority: 2 },
  'telegram-intel': { name: 'Telegram Intel', enabled: false, priority: 2 },
  'airline-intel': { name: 'Airline Intelligence', enabled: false, priority: 2 },
  'tech-readiness': { name: 'Tech Readiness Index', enabled: false, priority: 2 },
  'world-clock': { name: 'World Clock', enabled: false, priority: 2 },
  'national-debt': { name: 'Global Debt Clock', enabled: false, priority: 2 },
  'cross-source-signals': { name: 'Cross-Source Signals', enabled: true, priority: 2 },
  'market-implications': { name: 'AI Market Implications', enabled: false, priority: 1 },
  deduction: { name: 'Deduct Situation', enabled: false, priority: 1 },
  'geo-hubs': { name: 'Geopolitical Hubs', enabled: false, priority: 2 },
  'tech-hubs': { name: 'Hot Tech Hubs', enabled: false, priority: 2 },
  'positive-feed': { name: 'Good News Feed', enabled: false, priority: 1 },
  progress: { name: 'Human Progress', enabled: false, priority: 1 },
  counters: { name: 'Live Counters', enabled: false, priority: 1 },
  spotlight: { name: "Today's Hero", enabled: false, priority: 1 },
  breakthroughs: { name: 'Breakthroughs', enabled: false, priority: 1 },
  digest: { name: '5 Good Things', enabled: false, priority: 1 },
  species: { name: 'Conservation Wins', enabled: false, priority: 1 },
  renewable: { name: 'Renewable Energy', enabled: false, priority: 1 },
  'commodity-news': { name: 'Commodity News', enabled: true, priority: 1 },
  'gold-silver': { name: 'Gold & Silver', enabled: false, priority: 1 },
  'mining-news': { name: 'Mining News', enabled: false, priority: 1 },
  'critical-minerals': { name: 'Critical Minerals', enabled: false, priority: 1 },
  'base-metals': { name: 'Base Metals', enabled: false, priority: 1 },
  'mining-companies': { name: 'Mining Companies', enabled: false, priority: 1 },
  'commodity-regulation': { name: 'Regulation & Policy', enabled: false, priority: 1 },
  'gcc-investments': { name: 'GCC Investments', enabled: false, priority: 2 },
  startups: { name: 'Startups & VC', enabled: false, priority: 1 },
  vcblogs: { name: 'VC Insights & Essays', enabled: false, priority: 1 },
  regionalStartups: { name: 'Global Startup News', enabled: false, priority: 1 },
  unicorns: { name: 'Unicorn Tracker', enabled: false, priority: 1 },
  accelerators: { name: 'Accelerators & Demo Days', enabled: false, priority: 1 },
  security: { name: 'Cybersecurity', enabled: false, priority: 1 },
  policy: { name: 'AI Policy & Regulation', enabled: false, priority: 1 },
  regulation: { name: 'Financial Regulation', enabled: false, priority: 2 },
  hardware: { name: 'Semiconductors & Hardware', enabled: false, priority: 2 },
  cloud: { name: 'Cloud & Infrastructure', enabled: false, priority: 2 },
  dev: { name: 'Developer Community', enabled: false, priority: 2 },
  github: { name: 'GitHub Trending', enabled: false, priority: 1 },
  ipo: { name: 'IPOs, Earnings & M&A', enabled: false, priority: 1 },
  funding: { name: 'Funding & VC', enabled: false, priority: 1 },
  producthunt: { name: 'Product Hunt', enabled: false, priority: 1 },
  events: { name: 'Tech Events', enabled: false, priority: 1 },
  'internet-disruptions': { name: 'Internet Disruptions', enabled: false, priority: 2 },
  'service-status': { name: 'Service Status', enabled: false, priority: 2 },
  'ai-regulation': { name: 'AI Regulation Dashboard', enabled: false, priority: 2 },
  'markets-news': { name: 'Markets News', enabled: false, priority: 2 },
  forex: { name: 'Forex & Currencies', enabled: false, priority: 1 },
  bonds: { name: 'Fixed Income', enabled: false, priority: 1 },
  'commodities-news': { name: 'Commodities News', enabled: false, priority: 2 },
  'crypto-news': { name: 'Crypto News', enabled: false, priority: 2 },
  'crypto-heatmap': { name: 'Crypto Sectors', enabled: false, priority: 1 },
  'defi-tokens': { name: 'DeFi Tokens', enabled: false, priority: 2 },
  'ai-tokens': { name: 'AI Tokens', enabled: false, priority: 2 },
  'other-tokens': { name: 'Alt Tokens', enabled: false, priority: 2 },
  centralbanks: { name: 'Central Bank Watch', enabled: false, priority: 1 },
  'economic-news': { name: 'Economic News', enabled: false, priority: 2 },
  derivatives: { name: 'Derivatives & Options', enabled: false, priority: 2 },
  fintech: { name: 'Fintech & Trading Tech', enabled: false, priority: 2 },
  institutional: { name: 'Hedge Funds & PE', enabled: false, priority: 2 },
  analysis: { name: 'Market Analysis', enabled: false, priority: 2 },
  gccNews: { name: 'GCC Business News', enabled: false, priority: 2 },
};

export const FULL_MAP_LAYERS: MapLayers = {
  iranAttacks: !_desktop,
  gpsJamming: false,
  satellites: false,
  conflicts: true,
  bases: !_desktop,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: true,
  nuclear: true,
  irradiators: false,
  radiationWatch: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: true,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  diseaseOutbreaks: false,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: true,
  ciiChoropleth: false,
  dayNight: false,
  miningSites: false,
  processingPlants: false,
  commodityPorts: true,
  webcams: false,
  weatherRadar: false,
};

export const FULL_MOBILE_MAP_LAYERS = FULL_MAP_LAYERS;

export const ALL_PANELS: Record<string, PanelConfig> = { ...FULL_PANELS };
export const VARIANT_DEFAULTS: Record<string, string[]> = { full: Object.keys(FULL_PANELS) };
export const VARIANT_PANEL_OVERRIDES: Partial<Record<string, Partial<Record<string, Partial<PanelConfig>>>>> = {};

export function getEffectivePanelConfig(key: string, _variant: string): PanelConfig {
  return ALL_PANELS[key] || { name: key, enabled: false, priority: 2 };
}

export function isPanelEntitled(_key: string, _config: PanelConfig): boolean {
  // Risk Sentinel: no premium tiers — all panels are always available
  return true;
}

export const DEFAULT_PANELS: Record<string, PanelConfig> = Object.fromEntries(
  (VARIANT_DEFAULTS[SITE_VARIANT] ?? VARIANT_DEFAULTS['full'] ?? []).map(key =>
    [key, getEffectivePanelConfig(key, SITE_VARIANT)]
  )
);

export const DEFAULT_MAP_LAYERS = FULL_MAP_LAYERS;
export const MOBILE_DEFAULT_MAP_LAYERS = FULL_MOBILE_MAP_LAYERS;

export const LAYER_TO_SOURCE: Partial<Record<keyof MapLayers, DataSourceId[]>> = {
  military: ['opensky', 'wingbits'],
  ais: ['ais'],
  natural: ['usgs'],
  weather: ['weather'],
  outages: ['outages'],
  cyberThreats: ['cyber_threats'],
  protests: ['acled', 'gdelt_doc'],
  ucdpEvents: ['ucdp_events'],
  displacement: ['unhcr'],
  climate: ['climate'],
  sanctions: ['sanctions_pressure'],
  radiationWatch: ['radiation'],
};

export const PANEL_CATEGORY_MAP: Record<string, { labelKey: string; panelKeys: string[]; variants?: string[] }> = {
  core: { labelKey: 'header.panelCatCore', panelKeys: ['map', 'live-news', 'insights', 'strategic-posture'] },
  customs: { labelKey: 'Customs & Trade', panelKeys: ['alert-feed', 'trade-policy', 'supply-chain', 'sanctions-pressure', 'commodities', 'economic-correlation'] },
  intelligence: { labelKey: 'Intelligence', panelKeys: ['cii', 'strategic-risk', 'intel', 'gdelt-intel', 'cascade', 'military-correlation'] },
};

export const MONITOR_COLORS = ['#44ff88', '#ff8844', '#4488ff', '#ff44ff', '#ffff44', '#ff4444', '#44ffff', '#88ff44', '#ff88ff', '#88ffff'];
export const STORAGE_KEYS = { panels: 'worldmonitor-panels', monitors: 'worldmonitor-monitors', mapLayers: 'worldmonitor-layers', disabledFeeds: 'worldmonitor-disabled-feeds' } as const;
